from tests.test_plots.test_base_plot import TestBasePlot
from tests.test_plots.test_hexagonal_plot import TestHexagonalPlot
from tests.test_plots.test_histogram_plot import TestHistogramPlot
from tests.test_plots.test_scatter_boxplot_plot import TestScatterBoxplotPlot
from tests.test_plots.test_scatter_interactive import TestScatterInteractivePlot
from tests.test_plots.test_scatter_static_plot import TestScatterStaticPlot
from tests.test_plots.test_trisurf_interactive_plot import TestTrisurfInteractivePlot
from tests.test_plots.test_trisurf_static_plot import TestTrisurfStaticPlot
