from tests.test_plots.test_hexagonal_plot import TestHexagonalPlot
from tests.test_plots.test_scatter_boxplot_plot import TestScatterBoxplotPlot
from tests.test_plots.test_scatter_density_plot import TestScatterDensityPlot
from tests.test_plots.test_scatter_interactive import TestScatterInteractivePlot
from tests.test_plots.test_scatter_static_plot import TestScatterStaticPlot
from tests.test_plots.test_trisurf_plot import TestTrisurfPlot
